# -*- coding: utf-8 -*-
"""551_demo

Download automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PxCGcB6NiQ_PM21VE4vJURJAEKnA5TTe
"""

import streamlit as st
import duckdb

FILE = "play_by_play_2025.parquet"

# Title & caption
st.title("NFL Analytics")
st.caption("Powered by DuckDB: Columnar OLAP on play-by-play data")

# Loading all players ONCE to not re-read the parquet file at each rerun
@st.cache_data # this function checks if the the func below has been ran,
               # If ran: returns the previously stored output
               # If not ran: reruns and returns the new output
def load_player_names():
  return duckdb.query(f"""
      SELECT DISTINCT receiver_player_name
      FROM '{FILE}'
      WHERE receiver_player_name IS NOT NULL
      ORDER BY receiver_player_name
  """).to_df()['receiver_player_name'].tolist()

all_players = load_player_names()

# Sidebar controls
mode = st.sidebar.selectbox("Mode", [
    "Player Total Stats",
    "Player Comparison Stats",
    "Team Total Stats",
    "Team Per-Game Avg"
])

season = st.sidebar.radio("Season Type", ["REG", "POST"])


# --- MODE 1: Player Total Stats ---
if mode == "Player Total Stats":
  st.header("Player Total Stats")

  # Stores the stat user selects
  stat = st.selectbox("Stat", [
      "receiving_yards",
      "rushing_yards",
      "touchdown"
  ])

  top_n = st.slider("Top N Players", 5, 25, 10) # Displays a slider for the dataframe limit

  df = duckdb.query(f"""
      SELECT receiver_player_name as player,
              SUM({stat}) as total
      FROM '{FILE}'
      WHERE season_type = '{season}'
        AND receiver_player_name IS NOT NULL
      GROUP BY receiver_player_name
      ORDER BY total DESC
      LIMIT {top_n}
  """).to_df()

  st.dataframe(df) # Displays an interactive dataframe
  st.bar_chart(df.set_index('player')) # Displays a bar chart for players and the chosen stat

  st.info("DuckDB only scanned 2 columns out of 300+. "
          "Since the database uses columnar storage, irrelevant columns are never read.")

  with st.expander("Show DuckDB execution plan"): # Opens a drop-down menu
    if st.button("Run EXPLAIN"): # Gives user option get the EXPLAIN execution plan
      plan = duckdb.query(f"""
      EXPLAIN SELECT receiver_player_name as player,
              SUM({stat}) as total
      FROM '{FILE}'
      WHERE season_type = '{season}'
        AND receiver_player_name IS NOT NULL
      GROUP BY receiver_player_name
      ORDER BY receiver_player_name DESC
      LIMIT {top_n}
  """).to_df()

      st.code(plan["explain_value"].iloc[0]) # Displays the execution plan in a readable, tree-format code block


# --- MODE 2: Player Comparison Stats ---
elif mode == "Player Comparison Stats":
  st.header("Player Comparison")

  # Separate display into 2 separate columns
  col1, col2 = st.columns(2)

  # Provides selectable dropdown menu of all players for both columns
  player1 = col1.selectbox(
      "Player 1",
      all_players,
      index=all_players.index('P.Nacua')
  )

  player2 = col2.selectbox(
      "Player 2",
      all_players,
      index=all_players.index('J.Smith-Njigba')
  )

  stat = st.selectbox("Stat", ["receiving_yards", "touchdown"])

  df = duckdb.query(f"""
      SELECT receiver_player_name as player,
             SUM({stat}) as total
      FROM '{FILE}'
      WHERE receiver_player_name IN ('{player1}', '{player2}')
        AND season_type = '{season}'
        AND receiver_player_name IS NOT NULL
      GROUP BY player
  """).to_df()

  if df.empty:
    st.warning("No data found for this combination. Try a different stat or season.")

  else:
    st.dataframe(df)
    st.bar_chart(df.set_index("player"))

  st.info("DuckDB uses columnar predicate pushdown to only reads rows matching "
          "both player names and play type. This way unused data "
          "is never scanned or loaded onto memory.")

  with st.expander("Show DuckDB execution plan"):
    if st.button("Run EXPLAIN"):
      plan = duckdb.query(f"""
      EXPLAIN SELECT receiver_player_name as player,
             SUM({stat}) as total
      FROM '{FILE}'
      WHERE receiver_player_name IN ('{player1}', '{player2}')
        AND season_type = '{season}'
        AND receiver_player_name IS NOT NULL
      GROUP BY player
  """).to_df()
      st.code(plan['explain_value'].iloc[0])


# --- MODE 3: Team Total Stats ---
elif mode == "Team Total Stats":
  st.header("Team Total Stats")

  stat = st.selectbox("Stat", ['touchdown', 'rushing_yards', 'passing_yards'])

  top_n = st.slider("Top N teams", 5, 32, 10)

  df = duckdb.query(f"""
      SELECT posteam as team,
             SUM({stat}) as total
      FROM '{FILE}'
      WHERE season_type = '{season}'
        AND posteam IS NOT NULL
      GROUP BY posteam
      ORDER BY total DESC
      LIMIT {top_n}
  """).to_df()

  st.dataframe(df)
  st.bar_chart(df.set_index('team'))

  st.info("GROUP BY triggers DuckDB's vectorized hash aggregation, where the "
          "database sums batches of ~1024 rows in CPU cache since all columnar "
          "values have the same data type")

  with st.expander("Show DuckDB execution plan"):
    if st.button("Run EXPLAIN"):
      plan = duckdb.query(f"""
      EXPLAIN SELECT posteam as team,
             SUM({stat}) as total
      FROM '{FILE}'
      WHERE season_type = '{season}'
        AND posteam IS NOT NULL
      GROUP BY posteam
      ORDER BY total DESC
      LIMIT {top_n}
  """).to_df()
      st.code(plan['explain_value'].iloc[0])


# --- MODE 4: Team Comparison Stats ---
elif mode == "Team Per-Game Avg":
  st.header("Team Per-Game Averages")

  stat = st.selectbox("Stat", ['touchdown', 'passing_yards', 'rushing_yards'])

  top_n = st.slider("Top N Teams:", 5, 32, 10)

  df = duckdb.query(f"""
      SELECT posteam as team,
             SUM({stat}) as total,
             COUNT(DISTINCT game_id) as games,
             ROUND(SUM({stat})::FLOAT / COUNT(DISTINCT game_id), 2) as per_game
      FROM '{FILE}'
      WHERE season_type = '{season}'
        AND posteam IS NOT NULL
      GROUP BY posteam
      ORDER BY per_game DESC
      LIMIT {top_n}
  """).to_df()

  st.dataframe(df)
  # Sets team name as index and only keeps the "per_game" column
  st.bar_chart(df.set_index('team')['per_game'])

  st.info("COUNT(DISTINCT game_id) ensures no games are double-counted "
          "DuckDB computes the total and per_game averages in a single "
          "vectorized pass")

  with st.expander("Show DuckDB execution plan"):
    if st.button("Run EXPLAIN"):
      plan = duckdb.query(f"""
      EXPLAIN SELECT posteam as team,
             SUM({stat}) as total,
             COUNT(DISTINCT game_id) as games,
             ROUND(SUM({stat})::FLOAT / COUNT(DISTINCT game_id), 2) as per_game
      FROM '{FILE}'
      WHERE season_type = '{season}'
        AND posteam IS NOT NULL
      GROUP BY posteam
      ORDER BY per_game DESC
      LIMIT {top_n}
  """).to_df()
      st.code(plan['explain_value'].iloc[0])
